---
- name: Getting Started First Playbook Extended
  hosts: localhost
  gather_facts: true
  become: yes
  tasks:

    - name: Check python
      #command: "python --version 2>&1"
      command: "python --version"
      register: python_installed

    - name: Print Python version
      debug: 
        msg: "{{python_installed}}"

    - name: Print message
      debug:
        msg: Hello world

    - name: Install R
      ansible.builtin.apt:
        name: r-base
        state: present

    - name: Install ubuntu desktop
      ansible.builtin.apt:
        name: ubuntu-desktop
        state: present

    - name: Install remote Desktop connection
      ansible.builtin.apt:
        name: xrdp
        state: present

    - name: Enable remote Desktop connection
      ansible.builtin.systemd:
        name: xrdp
        enabled: yes

    - name: Create local folder for downloads
      file:
        path: ~/.local/rstudio
        state: directory
        mode: 0777

    - name: Get Rstudio package
      get_url:
        url: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2022.07.1-554-amd64.deb
        dest: ~/.local/rstudio/rstudio.deb
        mode: 0777
        checksum: sha256:74b9e7518266532480fc604c037c905a4e63e78f85d702f2aca7b558b4fcbc21

    - name: Install Rstudio dependencies
      ansible.builtin.apt:
        name: libnss3, libasound2
        state: present
        

    - name: Install Rstudio
      apt: deb="~/.local/rstudio/rstudio.deb"
       
