- name: Ensure a Desktop is installed
  ansible.builtin.apt:
    name: ubuntu-desktop
    state: present

- name: Install remote Desktop connection
  ansible.builtin.apt:
    name: xrdp
    state: present

- name: Check which python version is installed
  shell: "python3.10 --version"
  register: python_output
  ignore_errors: true

- name: Print Python version
  debug:
    msg: "{{python_output.stdout_lines}}"

- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
  when: python_output.stdout_lines | length == 0

- name: Add ppa key for python 3.10
  apt_repository:
    validate_certs: no
    repo: 'ppa:deadsnakes/ppa'
    state: present
  when: python_output.stdout_lines | length == 0

- name: Install Python 3.10.6
  ansible.builtin.apt:
    name: python3.10
  when: python_output.stdout_lines | length == 0

- name: Check which python version is installed
  shell: "python3.10 --version"
  register: python_output
  ignore_errors: true
- name: Print Python version
  debug:
    msg: "{{python_output}}"

- name: Install pip
  shell: curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
- name: Upgrade pip
  ansible.builtin.command: python3.10 -m pip install --upgrade pip
  when: python_output.stdout_lines | length > 0

- name: Install distutils
  ansible.builtin.apt:
    name: python3.10-distutils
  when: python_output.stdout_lines | length > 0

- name: Install PyQt5 dependencies
  ansible.builtin.apt:
    name: libxcb-xinerama0

- name: Checkout git iBridges to /opt
  become: true
  git:
    repo: https://github.com/chStaiger/iBridges-Gui.git
    dest: /opt/iBridges
    version: rsc-pyqt6
    force: true
  when: python_output.stdout_lines | length > 0

- name: Install pip requirements for iBridges
  ansible.builtin.command: python3.10 -m pip install -r /opt/iBridges/requirements.txt
  when: python_output.stdout_lines | length > 0

- name: Install desktop file menu item through role
  include_role:
    name: desktop_file
  vars:
    desktopfile_app_name: ibridges
    desktopfile_sizes:
      - 48
    desktopfile_login: true
