---
- name: Clean up results of first playbook
  hosts: localhost
  gather_facts: true
  become: yes
  tasks:

    - name: Check python
      shell: "python --version 2>&1"
      register: python_installed

    - name: Print Python version
      debug: 
        msg: "{{python_installed}}"

    - name: Print message
      debug:
        msg: Hello world

    - name: Remove Rstudio and its dependencies
      ansible.builtin.apt:
        name: libnss3, libasound2, rstudio
        state: absent

    - name: Enable remote Desktop connection
      ansible.builtin.systemd:
        name: xrdp
        enabled: no

    - name: Remove remote Desktop connection
      ansible.builtin.apt:
        name: xrdp
        state: absent

#    - name: Remove ubuntu desktop
#      ansible.builtin.apt:
#        name: ubuntu-desktop
#        state: absent

    - name: Remove R
      ansible.builtin.apt:
        name: r-base-core, r-base
        state: absent
   
    - name: Cleanup packakge manager
      ansible.builtin.apt:
        autoremove: yes
        clean: yes

    - name: Remove local folder for downloads
      file:
        path: ~/.local/rstudio
        state: absent
