---
- name: RAPID7 installer for Linux
  hosts: all
  gather_facts: true
  become: true
  vars_prompt:
    - name: token
      prompt: Enter token
    - name: co_name
      prompt: Enter CO name
      private: false
  roles:
    - rapid7
