---
- name: Create install directory /opt/rapid7
  file:
    path: /opt/rapid7
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Copy install script to /opt/rapid7
  copy: 
    src: "agent_installer-x86_64.sh"
    dest: "/opt/rapid7/agent_installer-x86_64.sh"
    mode: u+x

- name: Get workspace name
  ansible.builtin.shell: jq -r .workspace_name < /etc/rsc/workspace.json
  register: workspace_name
  changed_when: false

- name: Debug
  debug:
     var: workspace_name

- name: Set attributes
  ansible.builtin.set_fact:
    attributes: "{{ ['SurfResearchCloud', co_name, workspace_name.stdout] | map('regex_replace', '[^A-Za-z0-9_\\-=]', '') | list | join(',') }}"

- name: Debug
  debug:
    var: attributes

- name: Debug
  debug:
     var: token

- name: Install rapid7
  command: ./agent_installer-x86_64.sh install_start --token {{token}} --attributes "{{ attributes }}"
  args:
    chdir: "/opt/rapid7"
